version: '3'

services:
  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   command: 
  #     --default-authentication-plugin=mysql_native_password
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --init-file /docker-entrypoint-initdb.d/helloworld.sql # mysql 数据库初始化 sql 文件
  #   environment: # 通过环境变量设置密码
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: password
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./helloworld.sql:/docker-entrypoint-initdb.d/helloworld.sql # 挂载数据库初始化 sql 文件

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - 6379:6379
  
  # 当前容器域名，当前 compose 下的其它容器可通过 helloworld:8080 连接此容器
  helloworld:
    container_name: helloworld # 容器名
    # image: wengchaoxi/helloworld:0.1 # 使用 dockerhub 镜像
    build: ./helloworld # 指定本地构建目录构建镜像
    command: "./helloworld" # 容器中启动程序的命令
    # depends_on:
    #   - mysql
    #   - redis
    volumes:
      - ./helloworld/log/:/log/ # 挂载日志目录
    ports:
      - 8080:8080 # 端口映射（宿主机端口:容器端口）