version: '3'

services:
  # mysql:
  #   container_name: mysql
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   command: 
  #     --default-authentication-plugin=mysql_native_password
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --init-file /docker-entrypoint-initdb.d/helloworld.sql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: password
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./helloworld.sql:/docker-entrypoint-initdb.d/helloworld.sql

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - 6379:6379
  helloworld:
    container_name: helloworld
    # image: wengchaoxi/helloworld:0.1
    build: ./helloworld
    command: "./helloworld"
    # depends_on:
    #   - mysql
    #   - redis
    volumes:
      - ./helloworld/log/:/log/
    ports:
      - 8080:8080
